[package]
name = "pancake-scala-client-native"
version = "0.0.0"
authors = ["PancakeDB <inquiries@pancakedb.com>"]
edition = "2018"

[dependencies]
jni = "0.19"
pancake-db-idl = "0.0.0-alpha.0"
pancake-db-core = "0.0.0-alpha.0"
protobuf = "3.0.0-alpha.1"
q_compress = "0.3.1"

[lib]
crate-type = ["cdylib"]
